# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: acienciadalua-db
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# api:
#   image: ghcr.io/luizhenri16/auth_api:latest
#   ports:
#     - "3000:3000"
#   environment:
#     DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password123@db:5432/auth_db?schema=public}
#     JWT_SECRET: ${JWT_SECRET}
#     JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
#     NODE_ENV: production
#   depends_on:
#     - db

# volumes:
#  postgres_data:

services:
  db:
    image: postgres:15
    container_name: acienciadalua-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M

  api:
    build: .
    container_name: acienciadalua-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
      - ./uploads:/app/uploads
      - ./files:/app/files
    command: sh -c "npm install && npx prisma generate && npx prisma migrate dev && npm run start:dev"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
